name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

jobs:
  test:
    name: Test PG 12
    runs-on: ubuntu-latest
    container:
      image: timescaledev/rust-pgx:latest
      env:
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10
      options: -u root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20

    - name: Start Postgres
      run: |
        su postgres
        HOME=/home/postgres cargo pgx start pg12

    - name: Run Tests
      run: HOME=/home/postgres cargo pgx test pg12
