name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: timescaledev/rust-pgx:latest
      env:
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10
        HOME: /home/postgres

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20

    - name: Test 12
      run: HOME=/home/postgres cargo pgx test pg12
