name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

jobs:
  test:
    name: Test PG 12
    runs-on: ubuntu-latest
    container:
      image: timescaledev/rust-pgx:latest
      env:
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20

    - name: chown Repository
      run: chown -R postgres .

    - name: Run Tests
      run:  sudo -HEsu postgres sh -c "/usr/local/cargo/bin/cargo test pg12"
